version: '3.8'

services:
  # PostgreSQL Database for development
  postgres-dev:
    image: postgres:16-alpine
    container_name: mkan-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: mkan_dev
      POSTGRES_PASSWORD: mkan_dev_password
      POSTGRES_DB: mkandb_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mkan_dev -d mkandb_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache for development
  redis-dev:
    image: redis:7-alpine
    container_name: mkan-redis-dev
    restart: unless-stopped
    command: redis-server
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Adminer for database management
  adminer:
    image: adminer:latest
    container_name: mkan-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres-dev
    depends_on:
      - postgres-dev

volumes:
  postgres_dev_data:
    driver: local

networks:
  default:
    name: mkan-dev-network
    driver: bridge